### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dvzrv** [flatmax/gtkiostream#5]
Hi!
I would like to be able to move gtkiostream to Arch Linux' [community] repository.
It would be great if further releases of this software would be made :-)
Are there any roadmaps?

**Comment by flatmax** [comment]
Hey David,

I will endeavor to make a new release soon.

**Comment by dvzrv** [comment]
Any news on this? :)

**Comment by flatmax** [comment]
oh - is it possible to use master ? Would you prefer for me to do an official release ?

**Comment by flatmax** [comment]
I just created release v1.8.0
Please run autogen.sh and compile as per usual
