### ISSUE TITLE
./scripts/myAutoreconf.sh missing

### ISSUE THREAD

**Issue by HinTak** [flatmax/gtkiostream#7]
The readme seems very outdated - ./scripts/myAutoreconf.sh is missing, and there also seems to be a lot of mysterious problems like having upper case "*.H" for header files etc.

**Comment by HinTak** [comment]
okay, I worked out that it should be "tools/autotools.sh" instead. BTW, traditionally this is called "autogen.sh", located at the top level.

It mostly does what it is supposed to do, except these warnings:

```
$ sh tools/autotools.sh 
libtoolize  putting auxiliary files in '.'.
libtoolize  copying file './ltmain.sh'
libtoolize  putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize  copying file 'm4/libtool.m4'
libtoolize  copying file 'm4/ltoptions.m4'
libtoolize  copying file 'm4/ltsugar.m4'
libtoolize  copying file 'm4/ltversion.m4'
libtoolize  copying file 'm4/lt~obsolete.m4'
configure.ac 34: installing './compile'
configure.ac 29: installing './missing'
applications/Makefile.am  installing './depcomp'
test/Makefile.am 172: warning: '%'-style pattern rules are a GNU make extension
test/Makefile.am 136: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
```

I'll probably have a look around and do a pull at some stage.

**Comment by flatmax** [comment]
I have added a symbolic link from tools/autoTools.sh to autogen.sh

**Comment by HinTak** [comment]
Thanks.
